Dockers compose node sql
pcuerrier/BudgETS pull request #28
Opened 2020-10-15 15:54 UTC by GERMANPECHO

### Explication

*Explication rapide*
Dockersfile in order to set the work environments for NodeJS, MSQL, React ( BackEnd  & FrontEnd)
DockerCompose.yml in order to build the three instances.
Merged with the last commits from master.

### Checklist 
- [ ] Cette PR modifie la DB 
- [ ] J'ai testé mes changements

### À tester

- Install Dockers Docker-compose - up / Docker images/ Docker ps -a ( Docker running instances)
- 

### Screenshot

*Si on a un changement au frontend*

2020-10-18 21:09 UTC, the-spelletier requested changes
Je veux juste etre sur de pourquoi on a besoin d'une autre version de mysql?
Aussi peut etre mettre dans .gitignore certains fichiers qui ne sont pas pertinents? (ex : container.jpg)
Je suis pas sur pour quelle raison tu as rename db.tpl.js...

2020-10-18 21:09 UTC, the-spelletier commented on README.md
> +# BudgETS financière
non?

2020-10-18 21:09 UTC, the-spelletier commented on package.json
> +    "mysql": "^2.18.1",
Pourquoi si on a deja mysql2?

2020-10-20 00:09 UTC, GERMANPECHO commented on README.md
> +# BudgETS financière
bizarre je n'ai pas touche le readme. peut être la modif a reste après la resolution des confits. Le jpg va être enleve et db.js renamed,

2020-10-20 00:26 UTC, GERMANPECHO commented on package.json
> +    "mysql": "^2.18.1",
modif faits - commit pull request 28

2020-10-21 16:56 UTC, VeroBergeron submitted a review, later dismissed
Seems good to me

2020-10-21 16:56 UTC, VeroBergeron commented on docker-compose.yml
> +            - MYSQL_PASSWORD=samplepassword
Eventuellement on voudra surement pas avoir ça en clear ici

2020-10-25 17:18 UTC, the-spelletier requested changes

2020-10-25 17:18 UTC, the-spelletier commented on docker-compose.yml
> +         command: yarn start
On utilise pas yarn dans le backend

2020-11-04 05:29 UTC, michael-dowse commented on entrypoint.sh
>  npx sequelize db:migrate
C'est déjà fait dans clean-dev. Tu peux enlever ces 2 lignes.

2020-11-17 15:37 UTC, closed without merging