create expenses and revenues pages
pcuerrier/BudgETS pull request #49
Opened 2020-10-24 17:39 UTC by VeroBergeron

### Explication

*Explication rapide*

### Checklist 
- [ ] Cette PR modifie la DB 
- [x] J'ai testé mes changements

### À tester
- Page de revenus
- Page de dépenses
- Changer de budget sur une des pages
- Voir un budget sans catégories

### Screenshot

![revenues](https://user-images.githubusercontent.com/16781092/97088381-5eb92300-15fe-11eb-9f3f-6c29ab20f284.PNG)

2020-10-24 18:46 UTC, the-spelletier submitted a review, later dismissed

2020-10-26 15:48 UTC, pcuerrier requested changes

2020-10-26 15:48 UTC, pcuerrier commented on package.json
> +    "db:reset": "npx sequelize-cli db:drop && npx sequelize-cli db:create && npx sequelize-cli db:migrate && cross-env NODE_ENV=development npx sequelize-cli db:seed:all"
Mauvais merge avec le master. Tu veux l'ancienne ligne. Celle-ci génère un bug pour les tests.

2020-10-27 14:52 UTC, pcuerrier approved these changes

2020-10-27 16:58 UTC, the-spelletier approved these changes

2020-10-27 16:58 UTC, merged