4.0-BE-Requirements
pcuerrier/BudgETS pull request #55
Opened 2020-10-27 22:58 UTC by michael-dowse

### Explication

*Explication rapide*

### Checklist 
- [x] Cette PR modifie la DB 
- [ ] J'ai testé mes changements

### À tester

- 
- 

### Screenshot

*Si on a un changement au frontend*

2020-10-28 14:24 UTC, pcuerrier approved these changes

2020-10-28 14:33 UTC, pcuerrier requested changes

2020-10-28 14:33 UTC, pcuerrier commented on router.js
> +        '/api/budget/:id/clone',
Je changerai aussi les routes dans 09_clone.test.js.

2020-10-29 13:00 UTC, pcuerrier submitted a review, later dismissed

2020-10-29 18:16 UTC, the-spelletier approved these changes

2020-10-29 18:16 UTC, the-spelletier commented on controllers/entry.js
> +    // TODO add validation for member
Pas forcément, pas toutes les entrées sont liées a un membres (ex : revenus)

2020-10-29 18:17 UTC, pcuerrier approved these changes

2020-10-29 18:17 UTC, merged