10.0 be requirements
pcuerrier/BudgETS pull request #80
Opened 2020-11-11 00:18 UTC by michael-dowse

### Explication

*Explication rapide*

### Checklist 
- [x] Cette PR modifie la DB 
- [ ] J'ai testé mes changements

### À tester

- Il reste à implémenter/tester le create/update/delete + la validation du mois et de l'année (dans les limites des date du budget). La validation de date devrait aussi se faire pour le create/update d'entrée budgétaire.

### Screenshot

*Si on a un changement au frontend*

2020-11-11 16:14 UTC, pcuerrier requested changes

2020-11-11 16:14 UTC, pcuerrier commented on controllers/category.js
> +        console.log(c);
Peux-tu juste enlever tes console.log?

2020-11-13 21:09 UTC, michael-dowse commented on controllers/cashflow.js
> +    return res.sendStatus(404);
Parce qu'on n'a pas besoin de ce call. Mais il existe just in case.

2020-11-13 21:13 UTC, the-spelletier approved these changes

2020-11-13 21:13 UTC, VeroBergeron approved these changes

2020-11-13 21:15 UTC, merged